services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newpassword
    volumes:
      - ./db_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newpassword
      MYSQL_DATABASE: test
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

volumes:
  redis-data:
networks:
  backend: 