version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      MYSQL_USER: newuser
      MYSQL_PASSWORD: newpassword
      MYSQL_DATABASE: test
      MYSQL_HOST: db  # Use the internal Docker network name
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

volumes:
  redis-data:

networks:
  backend: