services:
  - name: chat-app
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_HOST
        value: db
      - key: MYSQL_USER
        value: newuser
      - key: MYSQL_PASSWORD
        value: newpassword
      - key: MYSQL_DATABASE
        value: test
    buildCommand: ./build.sh
    startCommand: ./start.sh
    autoDeploy: true
    dependsOn:
      - name: db
    
  - name: db
    type: web  # Render doesn't support "database" type, so treat it as "web"
    env: docker
    dockerfilePath: ""
    image: mysql:latest
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: password
      - key: MYSQL_DATABASE
        value: test
      - key: MYSQL_USER
        value: newuser
      - key: MYSQL_PASSWORD
        value: newpassword
    autoDeploy: true
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql  # MySQL data directory
    healthCheckPath: /health  # Custom health check if needed
    serviceDetails:
      port: 3306