services:
  - type: web
    name: go-chat-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_HOST
        value: db  # The service name of the MySQL instance
      - key: MYSQL_USER
        value: newuser
      - key: MYSQL_PASSWORD
        value: newpassword
      - key: MYSQL_DATABASE
        value: test
      - key: PORT
        value: 8080
    buildCommand: ./build.sh
    startCommand: ./start.sh
    autoDeploy: true

  - type: web  # Change from 'database' to 'web' to allow Docker image
    name: mysql-db
    runtime: docker
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: password
      - key: MYSQL_DATABASE
        value: test
      - key: MYSQL_USER
        value: newuser
      - key: MYSQL_PASSWORD
        value: newpassword
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
    autoDeploy: true