services:
  - name: chat-app
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_HOST
        value: db
      - key: MYSQL_USER
        value: newuser
      - key: MYSQL_PASSWORD
        value: newpassword
      - key: MYSQL_DATABASE
        value: test
    buildCommand: ./build.sh
    startCommand: ./start.sh
    autoDeploy: true
    dependsOn:
      - db
    
  - name: db
    type: database
    dockerfilePath: ""
    image: mysql:latest
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: password
      - key: MYSQL_DATABASE
        value: test
      - key: MYSQL_USER
        value: newuser
      - key: MYSQL_PASSWORD
        value: newpassword
    healthCheckPath: /
    disk:
      name: redis-data
      mountPath: /data
    startCommand: |
      mysqladmin ping -h 127.0.0.1
    autoDeploy: true
    serviceDetails:
      port: 3306