services:
  - type: web
    name: go-chat-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_HOST
        value: db  # The service name of the MySQL instance
      - key: MYSQL_USER
        value: newuser
      - key: MYSQL_PASSWORD
        value: newpassword
      - key: MYSQL_DATABASE
        value: test
      - key: PORT
        value: 8080  # Application's port
    buildCommand: ./build.sh  # Use your build.sh script
    startCommand: ./start.sh  # Use your start.sh script
    autoDeploy: true
    dependsOn:
      - name: db  # Depends on the MySQL database service

  - type: web
    name: db  # MySQL service
    runtime: docker
    image: mysql:latest
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: password
      - key: MYSQL_DATABASE
        value: test
      - key: MYSQL_USER
        value: newuser
      - key: MYSQL_PASSWORD
        value: newpassword
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql  # Persisting MySQL data
    serviceDetails:
      port: 3306